// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibrary;

namespace MusicLibrary.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20190325024802_Songs")]
    partial class Songs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicLibrary.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName");

                    b.Property<string>("ArtistName");

                    b.Property<string>("ImgPath");

                    b.Property<int>("ReleaseYear");

                    b.HasKey("AlbumID");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumID = 1, AlbumName = "Highway 61 Revisited", ArtistName = "Bob Dylan.", ImgPath = "", ReleaseYear = 1965 },
                        new { AlbumID = 2, AlbumName = "Apologies to the Queen Mary", ArtistName = "Wolf Parade", ImgPath = "", ReleaseYear = 2007 },
                        new { AlbumID = 3, AlbumName = "Dragonslayer", ArtistName = "Sunset Rubdown", ImgPath = "", ReleaseYear = 2011 }
                    );
                });

            modelBuilder.Entity("MusicLibrary.Models.Song", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumID");

                    b.Property<string>("SongName");

                    b.HasKey("SongID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Songs");

                    b.HasData(
                        new { SongID = 1, AlbumID = 1, SongName = "Like A Rolling Stone" },
                        new { SongID = 2, AlbumID = 1, SongName = "Tombstone Blues" },
                        new { SongID = 3, AlbumID = 1, SongName = "It Takes A Lot To Laugh, It Takes A Train To Cry" },
                        new { SongID = 4, AlbumID = 1, SongName = "From A Buick 6" },
                        new { SongID = 5, AlbumID = 1, SongName = "Ballad Of A Thin Man" },
                        new { SongID = 6, AlbumID = 1, SongName = "Queen Jane Approximately" },
                        new { SongID = 7, AlbumID = 1, SongName = "Highway 61 Revisited" },
                        new { SongID = 8, AlbumID = 1, SongName = "Just Like Tom Thumb's Blues" },
                        new { SongID = 9, AlbumID = 1, SongName = "Desolation Row" },
                        new { SongID = 10, AlbumID = 2, SongName = "You Are A Runner" },
                        new { SongID = 11, AlbumID = 2, SongName = "Modern World" },
                        new { SongID = 12, AlbumID = 2, SongName = "Grounds For Divorce" },
                        new { SongID = 13, AlbumID = 2, SongName = "We Built Another World" },
                        new { SongID = 14, AlbumID = 2, SongName = "Fancy Claps" },
                        new { SongID = 15, AlbumID = 2, SongName = "Same Ghost Every Night" },
                        new { SongID = 16, AlbumID = 2, SongName = "Shine A Light" },
                        new { SongID = 17, AlbumID = 2, SongName = "Dear Sons And Daughters Of Hungry Ghosts" },
                        new { SongID = 18, AlbumID = 2, SongName = "I'll Believe In Anything" },
                        new { SongID = 19, AlbumID = 2, SongName = "It's A Curse" },
                        new { SongID = 20, AlbumID = 2, SongName = "Dinner Bells" },
                        new { SongID = 21, AlbumID = 2, SongName = "This Heart's On Fire" },
                        new { SongID = 22, AlbumID = 3, SongName = "Silver Moons" },
                        new { SongID = 23, AlbumID = 3, SongName = "Idiot Heart" },
                        new { SongID = 24, AlbumID = 3, SongName = "Apollo And The Buffalo And Anna" },
                        new { SongID = 25, AlbumID = 3, SongName = "Black Swan" },
                        new { SongID = 26, AlbumID = 3, SongName = "Paper Lace" },
                        new { SongID = 27, AlbumID = 3, SongName = "You Go On Ahead" },
                        new { SongID = 28, AlbumID = 3, SongName = "Nightengale" },
                        new { SongID = 29, AlbumID = 3, SongName = "Dragon's Layor" }
                    );
                });

            modelBuilder.Entity("MusicLibrary.Models.Song", b =>
                {
                    b.HasOne("MusicLibrary.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
