// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibrary;

namespace MusicLibrary.Migrations
{
    [DbContext(typeof(AlbumContext))]
    partial class AlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicLibrary.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName");

                    b.Property<string>("ArtistName");

                    b.Property<int>("GenreID");

                    b.Property<string>("ImgPath");

                    b.Property<string>("Notes");

                    b.Property<int>("ReleaseYear");

                    b.Property<int>("RunTime");

                    b.HasKey("AlbumID");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumID = 1, AlbumName = "Highway 61 Revisited", ArtistName = "Bob Dylan.", GenreID = 1, ImgPath = "", ReleaseYear = 1965, RunTime = 85 },
                        new { AlbumID = 2, AlbumName = "Apologies to the Queen Mary", ArtistName = "Wolf Parade", GenreID = 1, ImgPath = "", ReleaseYear = 2007, RunTime = 91 },
                        new { AlbumID = 3, AlbumName = "Dragonslayer", ArtistName = "Sunset Rubdown", GenreID = 1, ImgPath = "", ReleaseYear = 2011, RunTime = 89 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
